sonar.organization=ricardo3m
sonar.projectKey=ricardo3m_fort-firewall

# Relative paths to source directories.
sonar.sources=src

# Vendored/third-party code should not be analyzed as our own.
sonar.exclusions=src/3rdparty/**
